// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"project/internal/auth"
	"project/pkg/casbin"
	"project/pkg/db/cache"
	"project/pkg/db/sqlx"
	"project/services/core/repo"
	"project/services/core/service"
	"project/services/core/web"

	"github.com/google/wire"
)

// Injectors from wire.go:

func initServer(config2 *CoreConfig) (*web.CoreHandlerRegistry, error) {
	serverConfig := config2.Server
	dbConfig := config2.DB
	db, err := sqlx.NewDBConn(dbConfig)
	if err != nil {
		return nil, err
	}
	assignmentUserRepoImpl, err := repo.NewAssignmentUserRepoImpl(db)
	if err != nil {
		return nil, err
	}
	redisClient, err := cache.NewRedisInstance(NewCacheConfig())
	if err != nil {
		return nil, err
	}
	assignmentUserServiceImpl, err := service.NewAssignmentUserServiceImpl(assignmentUserRepoImpl, redisClient)
	if err != nil {
		return nil, err
	}
	coreHandlerRegistryOptions := web.CoreHandlerRegistryOptions{
		Config:                serverConfig,
		AssignmentUserService: assignmentUserServiceImpl,
	}
	coreHandlerRegistry := web.NewCoreHandlerRegistry(coreHandlerRegistryOptions)
	return coreHandlerRegistry, nil
}

// wire.go:

var CoreModuleSet = wire.NewSet(wire.FieldsOf(new(*CoreConfig), "server", "db"), NewCacheConfig, cache.NewRedisInstance, casbin.InitCasbin, sqlx.NewDBConn, wire.Struct(new(web.CoreHandlerRegistryOptions), "*"), web.NewCoreHandlerRegistry, auth.NewAuthImpl, repo.NewAssignmentUserRepoImpl, wire.Bind(new(service.AssignmentUserRepo), new(*repo.AssignmentUserRepoImpl)), service.NewAssignmentUserServiceImpl, wire.Bind(new(service.AssignmentUserService), new(*service.AssignmentUserServiceImpl)))
